# Generated by Django 3.1 on 2020-08-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='msg',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
